# Generated by Django 5.0.1 on 2024-01-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('pub_date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('thumbnail', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
