# Generated by Django 5.0.1 on 2024-01-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_newsarticle_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
