# Generated by Django 5.0.1 on 2024-01-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_newsarticle_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticle',
            new_name='News',
        ),
    ]
