# Generated by Django 5.0.1 on 2024-01-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_rename_newsarticle_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(),
        ),
    ]
