# Generated by Django 5.0.1 on 2024-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_alter_news_source_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(),
        ),
    ]
