# Generated by Django 5.0.1 on 2024-01-23 08:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
    ]
