# Generated by Django 5.0.1 on 2024-01-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_alter_subscription_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('once_a_day', 'Once a Day'), ('twice_a_day', 'Twice a Day'), ('once_a_week', 'Once a Week')], default='immediately', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aggregator.email'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('email', 'keyword')},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
    ]
