# Generated by Django 5.0.1 on 2024-01-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_email_keyword_subscription_frequency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
