# Generated by Django 5.0.1 on 2024-01-29 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0013_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='frequency',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
