# Generated by Django 5.0.1 on 2024-01-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0014_alter_subscription_keyword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
