# Generated by Django 5.0.1 on 2024-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0016_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('keyword', models.CharField(max_length=255)),
                ('schedule', models.CharField(choices=[('immediately', 'Immediately'), ('once_a_day', 'Once a Day'), ('twice_a_day', 'Twice a Day'), ('once_a_week', 'Once a Week')], max_length=20)),
            ],
            options={
                'unique_together': {('email', 'keyword')},
            },
        ),
    ]
